### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by shertz43** [MiSTer-devel/Arcade-DonkeyKong_MiSTer#15]
Each time you clear a level the tune thats played is off / not correct.

**Comment by famiclone6502** [comment]
I owned an original Donkey Kong arcade machine, and I've noticed that the pitch is different for sound. Jumping over a barrel, or collecting items in the second level, it just sounds weird. Additionally, the overall lack of bass in the biggest difference I've noticed.

The game play does feel fine, just not the sound.

**Comment by rhester72** [comment]
The sound of the walk is off as well - there's actually some randomness to the actual sound.  This was discovered/addressed in MAME a while back when that driver was moved from samples to discrete audio drivers.

**Comment by 80sArcadeKid** [comment]
The sound is the only really remaining piece of the puzzle to make this core accurate. Hoping one day someone makes the effort to fix it.

**Comment by 80sArcadeKid** [comment]
Great news, can't wait to try out the fixes.

**Comment by 80sArcadeKid** [comment]
The sound is not fixed. I've investigated this more with a MAME v FPGA comparison video. I own an original PCB and MAME is definitely similar in sound to the PCB whereas Mister is off in lots of places.
https://youtu.be/PCD7DFL4Bek

I also think that maybe the rom version is off? Old versions of MAME had very red girders like the FPGA implementation. This is just a thought on why it may be so different.

**Comment by 80sArcadeKid** [comment]
Ok so to be more accurate I;ve done a direct PCB capture v FPGA comparison video. Same/similar issue but certainly some aspects a little closer.. maybe?
https://youtu.be/Ew6pSeNG07o

**Comment by 80sArcadeKid** [comment]
One last comparision to round this off, this time PCB v MAME, even though the MAME sound is quite a bit duller, the general tone is near identical. We want this on FPGA but with a nice crisp sound (maybe it was my PC settings for sound in MAME). Thanks for watching y'all, hope this helps.
https://youtu.be/TWlyx9lr114

**Comment by 80sArcadeKid** [comment]
OK very last video I promose, a more granular example to hopefully make it easier to compare when fixing.
https://youtu.be/fKtifT8Nexg

Seems to be two constant issues, the pitch of overall sound, and the jingles (digital not analog?) are very beepy and scratchy.

**Comment by 80sArcadeKid** [comment]
There is also this assume known
https://github.com/furrykef/dkdasm/blob/master/dkong-snd.asm
